object BuildPlugins {
    object Versions {
        const val kotlinVersion = "1.4.21"
        const val buildToolsVersion = "4.1.2"
        const val butterknifeVersion = "10.2.3"
        const val googleService = "4.3.4"
        const val firebase = "2.4.1"
        const val onesignal = "0.12.6"
        const val spotlessPlugin = "3.27.2"
        const val navigationArgsPlugin = "2.3.3"
    }

    const val androidGradlePlugin = "com.android.tools.build:gradle:${Versions.buildToolsVersion}"
    const val kotlinGradlePlugin = "org.jetbrains.kotlin:kotlin-gradle-plugin:${Versions.kotlinVersion}"
    const val butterknife = "com.jakewharton:butterknife-gradle-plugin:${Versions.butterknifeVersion}"
    const val googleService = "com.google.gms:google-services:${Versions.googleService}"
    const val firebaseCrashlytic = "com.google.firebase:firebase-crashlytics-gradle:${Versions.firebase}"
    const val onesignal = "gradle.plugin.com.onesignal:onesignal-gradle-plugin:${Versions.onesignal}"
    const val spotlessPlugin = "com.diffplug.spotless:spotless-plugin-gradle:${Versions.spotlessPlugin}"
    const val navigationArgsPlugin = "androidx.navigation:navigation-safe-args-gradle-plugin:${Versions.navigationArgsPlugin}"

    const val androidApplication = "com.android.application"
    const val kotlinAndroid = "kotlin-android"
    const val kotlinKapt = "kotlin-kapt"
    const val kotlinAndroidExtensions = "kotlin-android-extensions"
    const val gmsGoogleServices = "com.google.gms.google-services"
    const val onesignalGradle = "com.onesignal.androidsdk.onesignal-gradle-plugin"
    const val navigationSafeArgs = "androidx.navigation.safeargs.kotlin"
    const val googleFirebaseCrashlytics = "com.google.firebase.crashlytics"
}

object AndroidSdk {
    const val minSdk = 21
    const val compile = 29
    const val target = compile
    const val versionCode = 21
    const val versionName = "0.22"
}

object KeyStore {
    const val storeFile = "posgo"
    const val storePassword = "Posgo!@#"
    const val keyAlias = "posgo"
    const val keyPassword = "Posgo!@#"
}

object Url {
    const val apiBaseDev = "https://api2-dev.abicommodity.co.id/v1/"
    const val apiBaseProd = "https://api2.abicommodity.co.id/v1/"
    const val urlDev = "https://api2-dev.abicommodity.co.id"
    const val urlProd = "https://api2.abicommodity.co.id"
    const val apiGtm = "https://api1.goldtomecca.com/v1/"
    const val apiDistrict = "https://dev.farizdotid.com/api/"
    const val apiGeo = "https://asia-southeast1-quiet-stacker-245710.cloudfunctions.net/"
    const val dbName = "appDb"
}

object Libraries {
    private object Versions {
        const val ktx = "1.1.0-alpha05"
        const val appcompat = "1.2.0"
        const val cardview = "1.0.0"
        const val material = "1.3.0-alpha01"
        const val recyclerview = "1.1.0"
        const val pallete = "1.0.0"
        const val sdp = "1.0.6"
        const val ssp = "1.0.6"
        const val constraint = "2.0.4"
        const val gif = "1.2.19"
        const val timeline = "1.1.3"
        const val gson = "2.8.6"
        const val retrofit2 = "2.7.2"
        const val glide = "4.11.0"
        const val multidex = "1.0.3"
        const val core = "1.3.2"
        const val lifecycle22 = "2.2.0"
        const val kotlin = "1.4.0"
        const val crashlytics = "17.3.0"
        const val analytics = "18.0.1"
        const val onesignal = "3.13.1"
        const val coroutines = "1.4.1"
        const val lifecycle23 = "2.3.0-alpha07"
        const val koin = "2.1.6"
        const val room = "2.3.0"
        const val timber = "4.7.1"
        const val joda = "2.10.3"
        const val paperdb = "2.6"
        const val dexter = "6.2.2"
        const val paging = "2.1.2"
        const val navigation = "2.3.3"
        const val biometric = "1.1.0"
        const val pinview = "1.4.3"
        const val circleImg = "3.1.0"
        const val okhttp = "4.8.1"
        const val retrofitMock = "2.0.2"
        const val signaturePad = "1.3.1"
        const val lottie = "3.6.0"
        const val jsoup = "1.13.1"
        const val shimmer = "0.5.0"
        const val preference = "1.1.1"
        const val stepview = "1.5.1"
        const val socketio = "1.0.0"
        const val loopVp = "0.2.0"
        const val stepper = "2.0.0-alpha"
        const val liveChat = "v2.0.3"
        const val ticketview = "1.1.2"
    }

    const val appCompat = "androidx.appcompat:appcompat:${Versions.appcompat}"
    const val cardview = "androidx.cardview:cardview:${Versions.cardview}"
    const val androidMaterial = "com.google.android.material:material:${Versions.material}"
    const val recyclerview = "androidx.recyclerview:recyclerview:${Versions.recyclerview}"
    const val palleteKtx = "androidx.palette:palette-ktx:${Versions.pallete}"
    const val sdp = "com.intuit.sdp:sdp-android:${Versions.sdp}"
    const val ssp = "com.intuit.ssp:ssp-android:${Versions.ssp}"
    const val constraintLayout = "androidx.constraintlayout:constraintlayout:${Versions.constraint}"
    const val gifDrawable = "pl.droidsonroids.gif:android-gif-drawable:${Versions.gif}"
    const val gson = "com.google.code.gson:gson:${Versions.gson}"
    const val retrofit = "com.squareup.retrofit2:retrofit:${Versions.retrofit2}"
    const val retrofitGson = "com.squareup.retrofit2:converter-gson:${Versions.retrofit2}"
    const val retrofitScalars = "com.squareup.retrofit2:converter-scalars:${Versions.retrofit2}"
    const val glide = "com.github.bumptech.glide:glide:${Versions.glide}"
    const val glideCompiler = "com.github.bumptech.glide:compiler:${Versions.glide}"
    const val multidex = "com.android.support:multidex:${Versions.multidex}"
    const val coreKtx = "androidx.core:core-ktx:${Versions.core}"
    const val lifecycleVM = "androidx.lifecycle:lifecycle-viewmodel-ktx:${Versions.lifecycle22}"
    const val lifecycleExt = "androidx.lifecycle:lifecycle-extensions:${Versions.lifecycle22}"
    const val stdlibKotlin = "org.jetbrains.kotlin:kotlin-stdlib-jdk7:${Versions.kotlin}"
//    const val crashlytics = "com.google.firebase:firebase-crashlytics-ktx:${Versions.crashlytics}"
//    const val analytics = "com.google.firebase:firebase-analytics-ktx:${Versions.analytics}"
    const val onesignal = "com.onesignal:OneSignal:${Versions.onesignal}"
    const val coroutinesCore = "org.jetbrains.kotlinx:kotlinx-coroutines-core:${Versions.coroutines}"
    const val coroutinesAndroid = "org.jetbrains.kotlinx:kotlinx-coroutines-android:${Versions.coroutines}"
    const val lifecycleLiveData = "androidx.lifecycle:lifecycle-livedata-ktx:${Versions.lifecycle23}"
    const val lifecycleRuntime = "androidx.lifecycle:lifecycle-runtime-ktx:${Versions.lifecycle23}"
    const val koinAndroid = "org.koin:koin-android:${Versions.koin}"
    const val koinAndroidScope = "org.koin:koin-androidx-scope:${Versions.koin}"
    const val koinAndroidViewModel = "org.koin:koin-androidx-viewmodel:${Versions.koin}"
    const val koinAndroidExt = "org.koin:koin-androidx-ext:${Versions.koin}"
    const val roomRuntime = "androidx.room:room-runtime:${Versions.room}"
    const val roomCompiler = "androidx.room:room-compiler:${Versions.room}"
    const val roomKtx = "androidx.room:room-ktx:${Versions.room}"
    const val timber = "com.jakewharton.timber:timber:${Versions.timber}"
    const val joda = "net.danlew:android.joda:${Versions.joda}"
    const val paperdb = "io.paperdb:paperdb:${Versions.paperdb}"
    const val dexter = "com.karumi:dexter:${Versions.dexter}"
    const val pagingRuntime = "androidx.paging:paging-runtime-ktx:${Versions.paging}"
    const val navFragment = "androidx.navigation:navigation-fragment-ktx:${Versions.navigation}"
    const val navUI = "androidx.navigation:navigation-ui-ktx:${Versions.navigation}"
    const val circleImgView = "de.hdodenhof:circleimageview:${Versions.circleImg}"
    const val okhttp = "com.squareup.okhttp3:okhttp:${Versions.okhttp}"
    const val okhttpLogging = "com.squareup.okhttp3:logging-interceptor:${Versions.okhttp}"
    const val retrofitMock = "com.squareup.retrofit2:retrofit-mock:${Versions.retrofitMock}"
    const val lottie = "com.airbnb.android:lottie:${Versions.lottie}"
    const val jsoup = "org.jsoup:jsoup:${Versions.jsoup}"
    const val shimmer = "com.facebook.shimmer:shimmer:${Versions.shimmer}"
    const val preferenceKtx = "androidx.preference:preference-ktx:${Versions.preference}"
}

object TestLibraries {
    private object Versions {
        const val junit4 = "4.13"
        const val testRunner = "1.3.0"
        const val espresso = "3.3.0"
    }

    const val junit4     = "junit:junit:${Versions.junit4}"
    const val testRunner = "androidx.test:runner:${Versions.testRunner}"
    const val espresso   = "androidx.test.espresso:espresso-core:${Versions.espresso}"
}